image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - pages
  - publish
  - scan

include:
  - project: ska-telescope/templates-repository
    file:
      - gitlab-ci/includes/docs.gitlab-ci.yml
      - gitlab-ci/includes/finaliser.gitlab-ci.yml
      - gitlab-ci/includes/helm-chart.gitlab-ci.yml
      - gitlab-ci/includes/k8s.gitlab-ci.yml
      - gitlab-ci/includes/oci-image.gitlab-ci.yml
      - gitlab-ci/includes/python.gitlab-ci.yml
      - gitlab-ci/includes/release.gitlab-ci.yml

k8s-test:
  rules:
    - when: never

stop-k8s-test:
  rules:
    - when: never
