[tool.poetry]
name = "ska-low-csp-testware"
version = "0.1.0"
description = ""
authors = ["Sander Ploegsma <sander.ploegsma@topic.nl>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.scripts]
vis_receiver = 'ska_low_csp_testware.vis_receiver:main'

[[tool.poetry.source]]
name = "skao"
url = "https://artefact.skao.int/repository/pypi-internal/simple"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.10"
pytango = "^10.0.0"
ska-ser-logging = "^0.4.3"
netifaces = "^0.11.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
flake8 = "^7.1.0"
isort = "^5.13.2"
pylint = "^3.2.6"
pylint-junit = "^0.3.4"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
coverage = "^7.6.0"
pytest-cov = "^5.0.0"
ska-tango-testing = "^0.7.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
ska-ser-sphinx-theme = "^0.1.2"
sphinx-autoapi = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
