global:
  exposeAllDS: true
  minikube: false
  operator: true

taranta:
  enabled: true

ska-tango-base:
  enabled: true

ska-low-csp-testware:
  global:
    annotations:
      k8s.v1.cni.cncf.io/networks: ska-low-csp-ci/cbf-pst

  image:
    registry: registry.gitlab.com/ska-telescope/ska-low-csp-testware
    tag: 0.0.1-dev.cf2388254

  packet_capture:
    interface: net1

  deviceServers:
    packet_capture:
      nodeSelector:
        kubernetes.io/hostname: clp-k8s-fpga-worker-1

  annotations:
    k8s.v1.cni.cncf.io/networks: ska-low-csp-ci/cbf-pst

  tolerations:
    - key: skao.int/node-type
      value: low-cbf-fpga
