display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-low-csp
telescope: SKA-low

labels:
  app: ska-low-csp-testware

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"
  DEBUG: 5678

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.4.3
    pullPolicy: IfNotPresent

image:
  registry: artefact.skao.int
  image: ska-low-csp-testware
  tag: 0.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m # 100m = 0.1 CPU
    memory: 128Mi # 128Mi = 0.12 GB mem
    ephemeral-storage: 256Mi
  limits:
    cpu: 150m # 150m = 0.15 CPU
    memory: 256Mi # 256Mi = 0.25 GB mem
    ephemeral-storage: 512Mi

deviceServers:
  vis-spead-unpacker:
    instances: ["1"]
    file: data/vis-spead-unpacker.yaml

nodeSelector: {}

affinity: {}

tolerations: []
