display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-low-csp
telescope: SKA-low

labels:
  app: ska-low-csp-testware

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"
  DEBUG: 5678

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.4.3
    pullPolicy: IfNotPresent

image:
  registry: artefact.skao.int
  image: ska-low-csp-testware
  tag: 0.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 2
    memory: 8Gi
  limits:
    cpu: 4
    memory: 16Gi

pcap_reader:
  pcap_dir: /mnt/pcap-files

deviceServers:
  pcap-reader:
    name: "pcap-reader-{{.Release.Name}}"
    function: testware
    domain: ska-low-csp
    instances: ["1"]
    command: pcap_reader
    server:
      name: pcap_reader
      instances:
        - name: "1"
          classes:
            - name: PcapReader
              devices:
                - name: "low-csp/testware/pcap-reader-1"
                  properties:
                    - name: pcap_dir
                      values:
                        - "{{.Values.pcap_reader.pcap_dir}}"
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.image.registry}}"
      image: "{{.Values.image.image}}"
      tag: "{{.Values.image.tag | default .Chart.AppVersion}}"
      pullPolicy: "{{.Values.image.pullPolicy}}"

nodeSelector: {}

affinity: {}

tolerations: []
