display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-low-csp
telescope: SKA-low

labels:
  app: ska-low-csp-testware

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"
  DEBUG: 5678

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.4.3
    pullPolicy: IfNotPresent

image:
  registry: artefact.skao.int
  image: ska-low-csp-testware
  tag: 0.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 2
    memory: 8Gi
  limits:
    cpu: 4
    memory: 16Gi

deviceServers:
  vis-spead-unpacker:
    name: "vis-spead-unpacker-{{.Release.Name}}"
    function: vis-spead-unpacker
    domain: ska-low-csp-testware
    instances: ["1"]
    command: "vis_spead_unpacker"
    server:
      name: "vis_spead_unpacker"
      instances:
        - name: "1"
          classes:
            - name: "VisSpeadUnpacker"
              devices:
                - name: "low-csp-test/vis-spead-unpacker/1"
                  properties:
                    - name: "pcap_dir"
                      values:
                        - "/pcap"
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.image.registry}}"
      image: "{{.Values.image.image}}"
      tag: "{{.Values.image.tag | default .Chart.AppVersion}}"
      pullPolicy: "{{.Values.image.pullPolicy}}"

  dynamic:
    name: "dynamic-{{.Release.Name}}"
    function: testing
    domain: ska-low-csp-testware
    instances: ["1"]
    command: dynamic_device
    server:
      name: dynamic_device
      instances:
        - name: "1"
          classes:
            - name: Parent
              devices:
                - name: test/parent/0
            - name: Child
              devices: []
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.image.registry}}"
      image: "{{.Values.image.image}}"
      tag: "{{.Values.image.tag | default .Chart.AppVersion}}"
      pullPolicy: "{{.Values.image.pullPolicy}}"

nodeSelector: {}

affinity: {}

tolerations: []
